services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=SUA_CHAVE_GEMINI
      - USE_CUDA=False
    volumes:
      - ./backend/users.json:/app/users.json
      - ./backend/tmp:/app/tmp 
      - ./backend/resumes_processed:/app/resumes_processed 
      - ./backend/chroma_langchain_db:/app/chroma_langchain_db
      - ./backend/:/app   
    ports:
      - "8000:8000"
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]