services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - USE_CUDA=${USE_CUDA}
    volumes:
      - ./backend/users.json:/app/users.json
      - ./backend/tmp:/app/tmp 
      - ./backend/resumes_processed:/app/resumes_processed 
      - ./backend/chroma_langchain_db:/app/chroma_langchain_db
      - ./backend/:/app   
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
              
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend