version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - GEMINI_API_KEY=AIzaSyBNY0Ys8BqiMnPQ6ajbmtfgqqjcjMf0VLw
    volumes:
      - ./backend/users.json:/app/users.json
      - ./backend/tmp:/app/tmp 
      - ./backend/:/app   
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
